### ISSUE TITLE
Can't compile project

### ISSUE THREAD

**Issue by akurtakov** [rgrunber/fedoraproject-p2#10]
mvn clean verify
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.fedoraproject.p2:xmvn-p2-installer-plugin:0.0.1-SNAPSHOT (/home/akurtakov/git/fedoraproject-p2/xmvn-p2-installer-plugin/pom.xml) has 7 errors
[ERROR]     Non-resolvable import POM: Failure to find org.fedoraproject.xmvn:xmvn-parent:pom:2.4.0 in http://mizdebsk.fedorapeople.org/xmvn/repo/ was cached in the local repository, resolution will not be reattempted until the update interval of xmvn has elapsed or updates are forced @ org.fedoraproject.p2:xmvn-p2-installer-plugin:[unknown-version], /home/akurtakov/git/fedoraproject-p2/xmvn-p2-installer-plugin/pom.xml, line 32, column 19 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for javax.inject:javax.inject:jar is missing. @ org.fedoraproject.p2:xmvn-p2-installer-plugin:[unknown-version], /home/akurtakov/git/fedoraproject-p2/xmvn-p2-installer-plugin/pom.xml, line 47, column 17
[ERROR]     'dependencies.dependency.version' for org.eclipse.sisu:org.eclipse.sisu.inject:jar is missing. @ org.fedoraproject.p2:xmvn-p2-installer-plugin:[unknown-version], /home/akurtakov/git/fedoraproject-p2/xmvn-p2-installer-plugin/pom.xml, line 52, column 17
[ERROR]     'dependencies.dependency.version' for org.sonatype.sisu:sisu-guice:jar:no_aop is missing. @ org.fedoraproject.p2:xmvn-p2-installer-plugin:[unknown-version], /home/akurtakov/git/fedoraproject-p2/xmvn-p2-installer-plugin/pom.xml, line 56, column 17
[ERROR]     'dependencies.dependency.version' for org.fedoraproject.xmvn:xmvn-install:jar is missing. @ org.fedoraproject.p2:xmvn-p2-installer-plugin:[unknown-version], /home/akurtakov/git/fedoraproject-p2/xmvn-p2-installer-plugin/pom.xml, line 66, column 17
[ERROR]     'dependencies.dependency.version' for org.slf4j:slf4j-simple:jar is missing. @ org.fedoraproject.p2:xmvn-p2-installer-plugin:[unknown-version], /home/akurtakov/git/fedoraproject-p2/xmvn-p2-installer-plugin/pom.xml, line 70, column 17
[ERROR]     'dependencies.dependency.version' for com.google.guava:guava:jar is missing. @ org.fedoraproject.p2:xmvn-p2-installer-plugin:[unknown-version], /home/akurtakov/git/fedoraproject-p2/xmvn-p2-installer-plugin/pom.xml, line 74, column 17
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by rgrunber** [comment]
We need a version of xmvn 2.4.0 somewhere but the repository we link to only provides 2.1.0. Normally an upstream project would build in this manner by pointing to the resource on maven central, but xmvn is not there. If one builds xmvn 2.4.0 locally first, then this would act as a workaround.

**Comment by akurtakov** [comment]
#12 adds README.md to make it obvious that local build/install is needed as XMvn authors plan on releasing only source and inside distros.
